#!/usr/bin/env python3

# make sure that path/to/gui_devel is on PYTHONPATH, example: export PYTHONPATH=~/PyPSUcurvetrace/gui_devel

try:
	import wx
	from setproctitle import setproctitle
	from curvetrace_mainGUI import curvetrace_app, fatal_error
	from curvetrace_constants import PROGRAM_NAME
	import logging

	import sys
	import threading
	import traceback

except ImportError as e:
	print ('Import error in curvetrace_gui: ' + str(e) )
	raise


#####################################################################


# Exception handler for main thread:
def excepthook_sys(*args):
	try:
		if len(args[0]) > 1:
			u = [ v for v in args[0] ]
			args = u
	except:
		pass
	fatal_error('Unexpected error', args)

# Exception handler for separate threads:
def excepthook_threading(args):
	wx.CallAfter(excepthook_sys, args)


#####################################################################


# main:
if __name__ == "__main__":

	# Install exception handlers:
	sys.excepthook = excepthook_sys
	threading.excepthook = excepthook_threading
	
	# Set up logging:
	logging.basicConfig(level=logging.DEBUG, format='%(relativeCreated)6d %(threadName)s: %(message)s')
	logging.debug ('**** SHOULD READ CONFIG FILE HERE... ****')

	
	# Set process name:
	setproctitle(PROGRAM_NAME)

	# Init the (wx)App:
	app = curvetrace_app() # init the app

	# Startup:
	app.startup() # start up: load config file, set up accoring to configs
	
	# Main event loop:
	app.MainLoop()
