#!/usr/bin/env python3

# This file is part of PyPSUcurvetrace, a toolbox for I/V curve tracing of electronic parts using programmable power supplies.
#
# PyPSUcurvetrace is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# PyPSUcurvetrace is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PyPSUcurvetrace.  If not, see <http://www.gnu.org/licenses/>.

import traceback
import sys
import argparse
# import configparser
# import datetime
import numpy as np
# import time
import matplotlib.pyplot as plt

from lib.read_datafile import read_datafile
from lib.plot_curves import plot_curves
from lib.curvetrace_tools import say_hello

################
# main program #
################

# parse input arguments (if any):
parser = argparse.ArgumentParser(description='curveplot is a Python program for plotting of PyPSUcurvetrace data.')
parser.add_argument('datafile')
parser.add_argument('-t','--type', help='Plot type. Format: <X><Y><C>, where X is the x-axis parameter, Y is the y-axis parameter, and C is the curves parameter; parameters are U1, I1, U2, I2. Example: -type U1I1U2. Default (if not format is not specified): type = U1I1U2')
parser.add_argument('-x','--xlabel', help='x-axis label')
parser.add_argument('-y','--ylabel', help='y-axis label')
args = parser.parse_args()

# Say Hello:
say_hello('curveplot', 'Plotting of PyPSUcurvetrace data')

# determine data file:
datafile = args.datafile

# determine plot type:
plot_type = 'U1I1U2' # default
if args.type:
	plot_type = args.type.upper()

# determine axis labels:
xlabel = None # default
ylabel = None # default
if args.xlabel:
	xlabel = args.xlabel
if args.ylabel:
	ylabel = args.ylabel

# load data from file:
data, label, T_val, T_tol = read_datafile(datafile)

# plot data:
plt.figure(figsize=(10, 7))
plot_curves( data = data,
             plot_type = plot_type,
             title = label,
             xlabel = xlabel,
             ylabel = ylabel)

plt.show()
