#!/usr/bin/env python3

import sys
import os
 
sys.path.append( str(os.path.realpath(os.path.dirname(__file__))) + "/../src/PyPSUcurvetrace/" )

from PyPSUcurvetrace.cprocess import cprocess
cprocess()
